"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
ans = 4613732 in 7.88e-05 s

"""

def fb(n:int = 4_000_000):
    i = 1
    prev = 1
    next = 1
    out = 0
    allSum = 0
    while i < n:
        out = prev + next
        i = out
        prev = next
        next = out
        if out%2 == 0:
            allSum += out
        
    return allSum

if __name__ == '__main__':
    print(fb())